quarkus.log.category."com.github.phoswald.fitbit.viewer".level=DEBUG
quarkus.rest-client.fitbit-api.url=https://api.fitbit.com

app.fitbit.client-id=${FITBIT_CLIENT_ID}
app.fitbit.client-secret=${FITBIT_CLIENT_SECRET}
app.fitbit.redirect-uri=http://localhost:8080/app/oauth/callback
