quarkus.rest-client.fitbit-api.url=https://api.fitbit.com

fitbit.client-id=${FITBIT_CLIENT_ID}
fitbit.client-secret=${FITBIT_CLIENT_SECRET}
fitbit.redirect-uri=http://localhost:8080/app/oauth/callback

quarkus.log.category."com.github.phoswald.fitbit.viewer".level=DEBUG
